### PR TITLE
Configuration options for hardcoded values

### PR DESCRIPTION
**Pull request by nstogner**
* Add `MESSENGER_ERROR_MAX_BACKOFF` config env var
* Add `AUTOSCALING_TIME_WINDOW` config env var
* Add `AUTOSCALING_INTERVAL` config env var

For time window calc see: https://go.dev/play/p/b2GdRzMJPUb

### CODE REVIEW

**Comment by nstogner** [comment]
Fixes #109

**Comment by nstogner** [comment]
Fixes #108

**Review by samos123 — APPROVED** [review]

**Comment by samos123** [comment]
Is setting `MESSENGER_ERROR_MAX_BACKOFF=0s` the same as turning of the backoff? Would that work?

**Comment by nstogner** [comment]
Yep, that should disable

**Pull request merged**
