### PR TITLE
GitHub action for creating release

### PR DESCRIPTION
**Pull request by samos123**

### CODE REVIEW

**Review by nstogner — COMMENTED** [review]
How is this different from the create-release button?

**Comment by samos123** [comment]
So all I need to do is `git tag v0.1.0 && git push` instead of doing that and then hoping I remember to do clicky clicky button.

**Comment by samos123** [comment]
@nstogner lets get this merged so our github project shows having releases with change logs whenever i push a new tag. I tested this out in vllm-docker project and it's very convenient.

**Comment by samos123** [comment]
Merging, can revert if you have a strong opinion against it.

**Pull request merged**
